### PR TITLE
RFC: Add a description field to StateLog

### PR DESCRIPTION
**Pull request by rajiteh**
This allows the user to set a description for each state change and store it in the db. The changes were influenced mostly by the PR discussions from https://github.com/gizmag/django-fsm-log/pull/5 

I'm looking for feedback on the approach and any alternative/better ideas on the impl. Thanks!

### CODE REVIEW

**Comment by hggh** [comment]
I like your idea. I'm looking forward to see that in fsm log.

**Comment by ticosax** [comment]
Hi,
thank you for the PR.
I will have a look within the next days hopefully.

**Comment by ticosax** [comment]
@rajiteh please can you fix the linter issue so codecov can execute ?

**Comment by rajiteh** [comment]
Closing in favour of #67

**Pull request closed without merging**
