### PR TITLE
Added a description field

### PR DESCRIPTION
**Pull request by mord4z**
Added a new field called description, the user can pass a parameter with
detailed data about the transition and save in state log table. Created
new migrations to
add the description field. Added a test

### CODE REVIEW

**Comment by ericntd** [comment]
The description field is exactly what I need, can someone merge this pull request?

**Comment by peterfarrell** [comment]
+1 on the need for this.

**Comment by mord4z** [comment]
Someone can merge this? @hzy ?

**Comment by ticosax** [comment]
I'm incline to reject this one as it is, because it is too intrusive I believe. A `description` field is something quite generic that could exists on the model on which you change the state. In this scenario `django_fsm_log` would be overriding this value as a side effect of calling any transition.
If you can think of something that wouldn't require to store state on the instance itself, then I think it would be a great addition.

**Comment by ticosax** [comment]
I'll close it, but know it can be re-open if you'd like to discuss more further.

**Comment by mord4z** [comment]
But if the description field exists in the model with the state field, the descriptions of the transitions will not be preserved in the log.
**Here is a use case:**
I send the same document to multiple branches, these should return it after processing.
Through description field, I can know which branch is returning me and what was done by each one in the document.

download

**Comment by ticosax** [comment]
Sorry I don't understand. Can you describe what I read in the screenshot ? Maybe you can take a screenshot in english ?

**Comment by mord4z** [comment]
Sorry, but the app not yet internationalized.
download

**Comment by ticosax** [comment]
I don't disagree with the goal, I think it would make sense to have `description` or `comment` on the transition logs. What I'm rejecting is the implementation proposal. If you can achieve the same without modifying state of the instance, then If think it has good chance to land.

**Pull request closed without merging**
