### PR TITLE
django 3.0 and python 3.8

### PR DESCRIPTION
**Pull request by imomaliev**
Dropped python 2 and django 1.8, test with django 3.0 and up, python 3.8

### CODE REVIEW

**Comment by wmusial** [comment]
fwiw, i'm using this, it works. thanks @imomaliev

**Comment by Dejna93** [comment]
@imomaliev Can you estimate me how many time do you need to merge it? I cant plan update my django app to newer version, because your package is still not working with django 3.0.

**Comment by imomaliev** [comment]
@Dejna93 I am not a collaborator of this repo. I can't merge this by myself. We need to wait until the current team will have time to merge this or give me access to do so.

**Comment by peterfarrell** [comment]
@blueyed Do you think you could merge this in and release to PyPi?

**Comment by luizlaydner** [comment]
It would be really great to see this PR merged and released !!!
Can't use django-fsm-log with django 3 !

**Comment by ticosax** [comment]
thx!

**Comment by ticosax** [comment]
pypi.org is timing out. I'll try later to push the package

**Comment by ticosax** [comment]
https://pypi.org/project/django-fsm-log/2.0.1/

**Pull request merged**
