### PR TITLE
Fix migrations: revert and squash

### PR DESCRIPTION
**Pull request by blueyed**
- revert change to 0003_statelog_description.py
- create a squashed migration

Fixes https://github.com/gizmag/django-fsm-log/issues/88.

### CODE REVIEW

**Comment by blueyed** [comment]
Not sure if that would really help though..
Given that 0002 is applied, it would not use the squashed migration, but 0003-0005 still (and therefore create the description non-null first AFAIK).

**Comment by blueyed** [comment]
Created a squashed migration for 0003-0005 only.

**Comment by scrampin** [comment]
I don't think the squashed migration is adding anything here. The most pressing need currently is to release a version of fsm log that does not include a rewritten migration, so as not to affect more people.

**Comment by blueyed** [comment]
The squashed migration is needed for when you have not applied 003 already.

@ticosax 
Can you create a new release again, please?

**Pull request merged**
